"""Single source of truth for scanner metadata.

Every other script reads from here. To add a scanner:
    1. Add an entry to SCANNERS below.
    2. (Optional) Add an extractor in extract_detail.py.
    3. (Optional) Add a render function in inject_renderers.py.
    4. Run rebuild_report.py.

Schema:
    - mode: "static" | "dynamic"
    - stack: "main" | "specialized" | "exclude" | "broken"
"""
from __future__ import annotations
from dataclasses import dataclass, field

@dataclass(frozen=True)
class Scanner:
    name: str
    mode: str
    type: str
    author: str
    license: str
    repo: str
    since: str = ""
    covers: tuple[str, ...] = ()
    what: str = ""
    how: str = ""
    when: str = ""
    pros: str = ""
    cons: str = ""
    alts: str = ""
    stack: str = "main"
    is_original: bool = False


SCANNERS: dict[str, Scanner] = {
    # ─── Original 14 (already in HTML; metadata here for STACKS computation) ─
    "syft":       Scanner("syft", "static", "SBOM", "Anchore", "Apache-2.0",
                          "https://github.com/anchore/syft", "2021",
                          covers=("sbom",), is_original=True),
    "trivy":      Scanner("trivy", "static", "Vuln (CVE+IaC+secrets+misconfig)",
                          "Aqua Security", "Apache-2.0",
                          "https://github.com/aquasecurity/trivy", "2019",
                          covers=("cve","iac","secrets","misconfig","sbom"), is_original=True),
    "grype":      Scanner("grype", "static", "Vuln (CVE)", "Anchore", "Apache-2.0",
                          "https://github.com/anchore/grype", "2020",
                          covers=("sbom","cve"), is_original=True),
    "dockle":     Scanner("dockle", "static", "Container Linter", "goodwithtech",
                          "Apache-2.0", "https://github.com/goodwithtech/dockle",
                          "2019", covers=("misconfig",), is_original=True),
    "trufflehog": Scanner("trufflehog", "static", "Secret (verified)",
                          "Truffle Security", "AGPL-3.0",
                          "https://github.com/trufflesecurity/trufflehog",
                          covers=("secrets",), is_original=True),
    "gitleaks":   Scanner("gitleaks", "static", "Secret (regex)", "Zachary Rice",
                          "MIT", "https://github.com/gitleaks/gitleaks",
                          covers=("secrets",), is_original=True, stack="specialized"),
    "clamav":     Scanner("clamav", "static", "Antivirus", "Cisco Talos", "GPLv2",
                          "https://www.clamav.net/", "2002",
                          covers=("malware",), is_original=True, stack="specialized"),
    "whatweb":    Scanner("whatweb", "dynamic", "Web Fingerprint", "urbanadventurer",
                          "GPLv3", "https://github.com/urbanadventurer/WhatWeb",
                          covers=("fingerprint",), is_original=True, stack="exclude"),
    "nmap":       Scanner("nmap", "dynamic", "Network Scanner",
                          "Gordon Lyon (Fyodor)", "NPSL", "https://nmap.org/", "1997",
                          covers=("network","fingerprint"), is_original=True),
    "nikto":      Scanner("nikto", "dynamic", "Web Vuln (legacy)", "Chris Sullo",
                          "GPLv2", "https://github.com/sullo/nikto",
                          covers=("web","misconfig"), is_original=True, stack="exclude"),
    "nuclei":     Scanner("nuclei", "dynamic", "Web Vuln (templates)",
                          "ProjectDiscovery", "MIT",
                          "https://github.com/projectdiscovery/nuclei",
                          covers=("web","cve","misconfig"), is_original=True),
    "wapiti":     Scanner("wapiti", "dynamic", "Web Vuln (DAST)", "Nicolas Surribas",
                          "GPLv2", "https://github.com/wapiti-scanner/wapiti",
                          covers=("web",), is_original=True, stack="exclude"),
    "zap":        Scanner("zap", "dynamic", "Web App (DAST + proxy)", "OWASP",
                          "Apache-2.0", "https://www.zaproxy.org/",
                          covers=("web",), is_original=True),
    "sqlmap":     Scanner("sqlmap", "dynamic", "SQLi specialized",
                          "Bernardo Damele · Miroslav Stampar", "GPLv2",
                          "https://sqlmap.org/", "2006",
                          covers=("web",), is_original=True, stack="specialized"),

    # ─── Phase 2: added scanners that cover a unique signal ─────────────
    "openvas":        Scanner("openvas", "dynamic", "Network Vuln (NASL)", "Greenbone",
                          "GPLv2", "https://www.openvas.org/", "2005",
                          covers=("network","cve"),
                          what="Greenbone Vulnerability Manager. 100k+ NASL plugins. Open-source equivalent to Nessus.",
                          how="Stack: GVM-Daemon + Manager + GSA web UI + OpenVAS scanner. NASL plugins (~100k) cover CVE checks, brute force, default creds, banner grab.",
                          when="Periodic scan of internal fleets (PCI-DSS, ISO 27001).",
                          pros="Immense coverage of CVEs in network services. Standard in compliance.",
                          cons="Heavy setup: bootstrap + feed sync takes 20-30 min. A full scan is ~39 min per target.",
                          alts="Nessus (commercial), Tenable.io, Qualys, Rapid7 InsightVM."),
    "osv":            Scanner("osv", "static", "Vuln (OSV.dev)", "Google", "Apache-2.0",
                          "https://github.com/google/osv-scanner", "2022",
                          covers=("cve","sbom"),
                          what="Scanner that matches packages against the OSV.dev database — an ecosystem-native advisory aggregator.",
                          how="Reads SBOMs/images via tarball; queries the osv.dev REST API to map version→advisory ID.",
                          when="Covers Go modules, Rust crates, Cargo where NVD tends to lag.",
                          pros="Ecosystem-native DB. Maintained by Google.",
                          cons="Lower coverage of OS packages than Trivy/Grype.",
                          alts="Trivy (broader), Grype (CVE-only)."),
    "secretscanner":  Scanner("secretscanner", "static", "Secrets (container)",
                          "Deepfence", "Apache-2.0",
                          "https://github.com/deepfence/SecretScanner", "2020",
                          covers=("secrets",),
                          what="Container-focused secret scanner. ~140 YARA-style rules.",
                          pros="Container-native, no need to export the FS.",
                          cons="The binary needs AVX2 — fails on old CPUs.",
                          alts="TruffleHog, GitLeaks, Whispers.", stack="broken"),
    "yara":           Scanner("yara", "static", "Malware/pattern", "VirusTotal",
                          "BSD-3", "https://github.com/VirusTotal/yara", "2007",
                          covers=("malware",),
                          what="Generic pattern-matching engine for classifying binaries and text.",
                          pros="Extensible with custom rules. Industry standard in malware research.",
                          cons="Rules must be written/curated.",
                          alts="ClamAV (signature-only), Capa.", stack="specialized"),
    "detect-secrets": Scanner("detect-secrets", "static", "Secrets (baseline)",
                          "Yelp", "Apache-2.0",
                          "https://github.com/Yelp/detect-secrets", "2018",
                          covers=("secrets",),
                          what="Baseline-diffable secret scanner — emits a JSON of the current state and diffs against future runs.",
                          pros="The baseline model reduces noise drastically.",
                          cons="Does not verify live. Plugins can have high FP rates.",
                          alts="TruffleHog, GitLeaks, Whispers."),
    "guarddog":       Scanner("guarddog", "static", "Supply-chain malware",
                          "Datadog", "Apache-2.0",
                          "https://github.com/DataDog/guarddog", "2022",
                          covers=("supplychain",),
                          what="Detects supply-chain malice in npm/PyPI packages.",
                          pros="The only scanner in the stack focused on malice (not vulnerability).",
                          cons="Limited to npm and PyPI.",
                          alts="Phylum, Snyk Advisor.", stack="broken"),
    "govulncheck":    Scanner("govulncheck", "static", "Vuln Go (reachability)",
                          "Google (Go team)", "BSD-3",
                          "https://go.dev/blog/vuln", "2022",
                          covers=("cve",),
                          what="CVE scanner for Go with reachability analysis.",
                          pros="The only reachability-aware scanner in the stack.",
                          cons="Go only.",
                          alts="Trivy, Grype.", stack="specialized"),
    "clair":          Scanner("clair", "static", "Vuln (CVE per layer)",
                          "Red Hat / Quay", "Apache-2.0",
                          "https://github.com/quay/clair", "2015",
                          covers=("cve",),
                          what="CVE scanner with a layer-by-layer indexed architecture.",
                          pros="Layer indexing gives natural dedup in registries.",
                          cons="The standalone clair-action requires a pre-downloaded DB.",
                          alts="Trivy, Grype.", stack="broken"),
    "dependency-check": Scanner("dependency-check", "static", "Vuln (CPE matching)",
                          "OWASP", "Apache-2.0",
                          "https://github.com/dependency-check/DependencyCheck", "2012",
                          covers=("cve",),
                          what="OWASP Dependency-Check: a CPE-based correlation engine against NVD.",
                          pros="OWASP project. NVD + OSS Index dual-feed.",
                          cons="Slow (NVD download ~30+ min).",
                          alts="Snyk, Trivy.", stack="broken"),
    "cdxgen":         Scanner("cdxgen", "static", "SBOM (OWASP)",
                          "OWASP CycloneDX", "Apache-2.0",
                          "https://github.com/CycloneDX/cdxgen", "2021",
                          covers=("sbom",),
                          what="CycloneDX 1.5 multi-language SBOM generator with VEX support.",
                          pros="Deep coverage in Maven/Gradle/Bazel.",
                          cons="Requires the build toolchain installed.",
                          alts="Syft, Microsoft SBOM Tool.", stack="broken"),
    "retire":         Scanner("retire", "static", "Vuln JS (hash/version)",
                          "Erlend Oftedal", "Apache-2.0",
                          "https://github.com/RetireJS/retire.js", "2013",
                          covers=("cve",),
                          what="retire.js: detects vulnerable JS libs by matching the hash/version of the .js files.",
                          pros="Detects vendored libs outside the dependency manifest.",
                          cons="Client-side JS only.",
                          alts="Trivy, npm audit, Snyk."),
    "whispers":       Scanner("whispers", "static", "Secrets (configs)",
                          "Adam Listek", "Apache-2.0",
                          "https://github.com/adeptex/whispers", "2019",
                          covers=("secrets",),
                          what="Whispers: a parser for structured configs (YAML/JSON/Dockerfile).",
                          pros="Structure-aware: fewer FPs than regex on YAML/JSON.",
                          cons="High sensitivity generates noise.",
                          alts="TruffleHog, GitLeaks, detect-secrets.", stack="specialized"),
    "kube-linter":    Scanner("kube-linter", "static", "K8s manifest issues",
                          "StackRox / Red Hat", "Apache-2.0",
                          "https://github.com/stackrox/kube-linter", "2020",
                          covers=("misconfig",),
                          what="StackRox kube-linter: lints Kubernetes YAMLs for best practices.",
                          pros="K8s-specific.",
                          cons="Skips silently if the image carries no YAML.",
                          alts="Trivy, Checkov, Polaris.", stack="broken"),
    "hadolint":       Scanner("hadolint", "static", "Dockerfile lint",
                          "Lukas Martinelli", "MIT",
                          "https://github.com/hadolint/hadolint", "2015",
                          covers=("misconfig",),
                          what="Hadolint: a Dockerfile linter with best-practice rules and shellcheck.",
                          pros="Shellcheck on the RUNs detects classes of unique bugs.",
                          cons="Dockerfile reconstruction via history loses COPY/ADD targets.",
                          alts="Dockle, Trivy --scanners config."),
    "checkov":        Scanner("checkov", "static", "IaC misconfig",
                          "Bridgecrew / Prisma", "Apache-2.0",
                          "https://github.com/bridgecrewio/checkov", "2019",
                          covers=("iac","misconfig"),
                          what="Checkov: 1000+ IaC + Dockerfile + SCA misconfig policies.",
                          pros="Broader coverage than Trivy/Dockle.",
                          cons="Heavy: 700MB image.",
                          alts="Trivy, tfsec, KICS."),
    "pip-audit":      Scanner("pip-audit", "static", "Vuln Python (PyPA)",
                          "PyPA", "Apache-2.0",
                          "https://github.com/pypa/pip-audit", "2022",
                          covers=("cve",),
                          what="pip-audit: an authoritative Python CVE scanner (PyPA Advisory DB).",
                          pros="Direct authority (PyPA).",
                          cons="Python only.",
                          alts="Safety, Snyk, Trivy.", stack="broken"),
    "httpx":          Scanner("httpx", "dynamic", "Web fingerprint",
                          "ProjectDiscovery", "MIT",
                          "https://github.com/projectdiscovery/httpx", "2020",
                          covers=("fingerprint","web"),
                          what="httpx: a fast web prober — fingerprint, TLS, JARM, CDN.",
                          pros="Fast. Multi-feature in a single binary.",
                          cons="Fingerprint only, not a vuln scan.",
                          alts="WhatWeb, Wappalyzer."),
    "jaeles":         Scanner("jaeles", "dynamic", "Web Vuln (signatures)",
                          "j3ssie", "MIT",
                          "https://github.com/jaeles-project/jaeles", "2019",
                          covers=("web",),
                          what="Jaeles: a template-driven web scanner, similar to Nuclei.",
                          pros="Template-driven.",
                          cons="Smaller community than Nuclei.",
                          alts="Nuclei, Wapiti.", stack="broken"),
    "arachni":        Scanner("arachni", "dynamic", "Web App (DAST)", "Sarosys",
                          "Arachni Public Source",
                          "https://github.com/Arachni/arachni", "2010",
                          covers=("web",),
                          what="Arachni: a Ruby DAST framework with deep checks for SQLi/XSS/RFI/LFI.",
                          pros="A complete suite similar to ZAP.",
                          cons="Archived project (last release 2017).",
                          alts="OWASP ZAP, Burp Suite, Wapiti."),
    "testssl":        Scanner("testssl", "dynamic", "TLS/SSL audit", "Dirk Wetter",
                          "GPLv2", "https://github.com/drwetter/testssl.sh", "2014",
                          covers=("network",),
                          what="testssl.sh: a comprehensive TLS/SSL audit via OpenSSL.",
                          pros="More detailed than Nessus/OpenVAS for TLS.",
                          cons="HTTP targets return a baseline of 'no TLS'.",
                          alts="sslyze, sslscan, Qualys SSL Labs.", stack="specialized"),
}


def by_stack(stack: str) -> list[str]:
    return sorted([s.name for s in SCANNERS.values() if s.stack == stack])


def by_mode(mode: str, exclude_broken: bool = True) -> list[str]:
    return sorted([s.name for s in SCANNERS.values()
                   if s.mode == mode and (not exclude_broken or s.stack != "broken")])
