#!/usr/bin/env bash
# Emit (on stdout) a `scanners` run config that points the Stage III pipeline at
# a given exposure_ranked.jsonl file. The ChimangoScan jsonl schema
# (repository_namespace / repository_name / tag_name) is understood natively by
# the scanners jsonl source -- no conversion is needed.
#
# Usage: make_scanners_config.sh RANKED_JSONL [LIMIT]
#   RANKED_JSONL  path to exposure_ranked.jsonl
#   LIMIT         max targets to seed (0 = no limit; used by the minimal test
#                 to cap the run at the top-N most exposed repositories)
set -euo pipefail

RANKED="${1:?usage: make_scanners_config.sh RANKED_JSONL [LIMIT]}"
LIMIT="${2:-0}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cat <<YAML
# Generated by orchestration/make_scanners_config.sh -- do not edit by hand.
queue:
  backend: sqlite
  sqlite_path: ${ROOT}/artifacts/queue.db

source:
  type: jsonl
  path: ${RANKED}
  limit: ${LIMIT}

scanners:
  static: true
  dynamic: true

workers:
  count: 4

output:
  dir: ${ROOT}/artifacts/out
YAML
